/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims.gui;

import com.sun.istack.internal.NotNull;

import ims.dto.City;
import ims.dto.Computing;
import ims.dto.Degree;
import ims.dto.EmployeePosition;
import ims.dto.Folk;
import ims.dto.Foreignlanguage;
import ims.dto.Job;
import ims.dto.Learning;
import ims.dto.Nationality;
import ims.dto.Religion;
import ims.dto.Typestaff;
import ims.bll.CityBLL;
import ims.bll.ComputingBLL;
import ims.bll.DegreeBLL;
import ims.bll.DeparmentBLL;
import ims.bll.FolkBLL;
import ims.bll.ForeignLanguageBLL;
import ims.bll.LearningBLL;
import ims.bll.JobBLL;
import ims.bll.NationalityBLL;
import ims.bll.PositionBLL;
import ims.bll.ReligionBLL;
import ims.bll.TypeStaffBLL;
import ims.util.UtilClass;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author NAT
 */
public final class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public static enum ACTION {INSERT, EDIT, VIEW};
    private ACTION action;
    private ims.dto.Employee employee;
    
    public Employee() {
        initComponents();
        setInfoDialog();
        action = ACTION.INSERT;
    }
    
    public Employee(@NotNull ims.dto.Employee employee,@NotNull ACTION action) {
        initComponents();
        setInfoDialog();
        this.action = action;
        this.employee = employee;
    }
    
    public  void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);        
        setResizable(false);
    }
    public void stateButton(boolean value){
        
        btNew.setVisible(value);
        btEdit.setVisible(value);
        btDelete.setVisible(value);
        btPrint.setVisible(value);
        btClose.setVisible(value);
        btSave.setVisible(!value);
        btCancel.setVisible(!value);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btNew = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEmployeeCode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNickName = new javax.swing.JTextField();
        chbGender = new javax.swing.JCheckBox();
        chbMarried = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBirthDay = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        combCity = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtPersonCode = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTakenCodeDay = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtTabernacle = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtBirthPlace = new javax.swing.JTextField();
        txtTakenCodePlace = new javax.swing.JTextField();
        txtNativeLand = new javax.swing.JTextField();
        txtMobie = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        combTypeStaff = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDateStart = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        combDeparment = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combJob = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combPosition = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCoefficient = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTakenLaborDay = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIdBank = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        combLearning = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        combDegree = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        combForeignLanguage = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        combComputing = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        combFolk = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        combNationality = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        combReligion = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtBaseSalary = new javax.swing.JFormattedTextField();
        txtSalary = new javax.swing.JFormattedTextField();
        txtAllowance = new javax.swing.JFormattedTextField();
        txtTakenLaborPlace = new javax.swing.JTextField();
        txtNumberLabor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btNew.setText("Thêm");
        btNew.setPreferredSize(new java.awt.Dimension(75, 23));
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        btEdit.setText("Sửa");
        btEdit.setPreferredSize(new java.awt.Dimension(75, 23));
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.setPreferredSize(new java.awt.Dimension(75, 23));

        btPrint.setText("In");
        btPrint.setPreferredSize(new java.awt.Dimension(75, 23));

        btClose.setText("Thoát");
        btClose.setPreferredSize(new java.awt.Dimension(75, 23));

        btSave.setText("Ghi");
        btSave.setPreferredSize(new java.awt.Dimension(75, 23));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Hủy");
        btCancel.setPreferredSize(new java.awt.Dimension(75, 23));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLayeredPane2.setLayout(new java.awt.GridBagLayout());

        jLabel17.setBackground(new java.awt.Color(0, 240, 240));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 30, 150));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thông tin cá nhân");
        jLabel17.setToolTipText("");
        jLabel17.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        jLayeredPane2.add(jLabel17, gridBagConstraints);

        jLabel18.setText("Mã nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel18, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        jLayeredPane2.add(txtEmployeeCode, gridBagConstraints);

        jLabel19.setText(" Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        jLayeredPane2.add(txtFullName, gridBagConstraints);

        jLabel20.setText(" Bí danh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        jLayeredPane2.add(txtNickName, gridBagConstraints);

        chbGender.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jLayeredPane2.add(chbGender, gridBagConstraints);

        chbMarried.setText("Có gia đình");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        jLayeredPane2.add(chbMarried, gridBagConstraints);

        jLabel21.setText("Di động");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel21, gridBagConstraints);

        jLabel22.setText(" Điện thoại nhà");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel22, gridBagConstraints);

        jLabel23.setText(" Địa chỉ Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel23, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtEmail, gridBagConstraints);

        jLabel24.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel24, gridBagConstraints);

        txtBirthDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtBirthDay.setToolTipText("MM/dd/yy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtBirthDay, gridBagConstraints);
        txtBirthDay.getAccessibleContext().setAccessibleDescription("");

        jLabel25.setText(" Nơi sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel25, gridBagConstraints);

        jLabel26.setText(" Tỉnh thành");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel26, gridBagConstraints);

        combCity.setModel(new DefaultComboBoxModel(
            new CityBLL().findCityEntities()
        ));
        combCity.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(combCity, gridBagConstraints);

        jLabel27.setText("CMND");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel27, gridBagConstraints);

        txtPersonCode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtPersonCode.setToolTipText("Chỉ nhập số");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtPersonCode, gridBagConstraints);

        jLabel28.setText(" Ngày cấp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel28, gridBagConstraints);

        txtTakenCodeDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtTakenCodeDay.setToolTipText("MM/dd/yy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtTakenCodeDay, gridBagConstraints);

        jLabel29.setText(" Nơi cấp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel29, gridBagConstraints);

        jLabel30.setText("Quê quán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel30, gridBagConstraints);

        jLabel31.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel31, gridBagConstraints);

        jLabel32.setText("Tạm trú");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane2.add(jLabel32, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtAddress, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtTabernacle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(jSeparator1, gridBagConstraints);

        jLabel46.setForeground(new java.awt.Color(255, 0, 0));
        jLabel46.setText("(*)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        jLayeredPane2.add(jLabel46, gridBagConstraints);

        jLabel47.setForeground(new java.awt.Color(255, 0, 0));
        jLabel47.setText("(*)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        jLayeredPane2.add(jLabel47, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtBirthPlace, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtTakenCodePlace, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtNativeLand, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtMobie, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane2.add(txtPhone, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLayeredPane1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 150));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin công việc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        jLayeredPane1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        jLayeredPane1.add(jSeparator2, gridBagConstraints);

        jLabel2.setText("Loại nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        jLayeredPane1.add(jLabel2, gridBagConstraints);

        combTypeStaff.setModel(new DefaultComboBoxModel(
            new TypeStaffBLL()
            .findTypeStaffEntities()
        ));
        combTypeStaff.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        jLayeredPane1.add(combTypeStaff, gridBagConstraints);

        jLabel3.setText(" Ngày vào làm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 25;
        jLayeredPane1.add(jLabel3, gridBagConstraints);

        txtDateStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        jLayeredPane1.add(txtDateStart, gridBagConstraints);

        jLabel4.setText(" Phòng ban");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        jLayeredPane1.add(jLabel4, gridBagConstraints);

        combDeparment.setModel(new DefaultComboBoxModel(
            new DeparmentBLL()
            .findDeparmentEntities()
        ));
        combDeparment.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jLayeredPane1.add(combDeparment, gridBagConstraints);

        jLabel5.setText("Công việc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        jLayeredPane1.add(jLabel5, gridBagConstraints);

        combJob.setModel(new DefaultComboBoxModel(
            new JobBLL().findJobEntities()
        )
    );
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combJob, gridBagConstraints);

    jLabel6.setText(" Chức vụ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel6, gridBagConstraints);

    combPosition.setModel(new DefaultComboBoxModel(
        new PositionBLL()
        .findEmployeePositionEntities()
    ));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combPosition, gridBagConstraints);

    jLabel7.setText("Mức lương CB");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel7, gridBagConstraints);

    jLabel8.setText(" Hệ số");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel8, gridBagConstraints);

    txtCoefficient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
    txtCoefficient.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtCoefficient.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtCoefficientKeyReleased(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtCoefficient, gridBagConstraints);

    jLabel9.setText(" Mức lương");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel9, gridBagConstraints);

    jLabel10.setText(" Phụ cấp lương");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 15;
    jLayeredPane1.add(jLabel10, gridBagConstraints);

    jLabel11.setText("Số sổ lao động");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel11, gridBagConstraints);

    jLabel12.setText(" Ngày cấp");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel12, gridBagConstraints);

    txtTakenLaborDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtTakenLaborDay, gridBagConstraints);

    jLabel13.setText(" Nơi cấp");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel13, gridBagConstraints);

    jLabel14.setText("TK.Ngân hàng");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel14, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtIdBank, gridBagConstraints);

    jLabel15.setText(" Ngân hàng");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel15, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtBank, gridBagConstraints);

    jLabel16.setText("Học vấn");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel16, gridBagConstraints);

    combLearning.setModel(new DefaultComboBoxModel(
        new LearningBLL()
        .findLearningEntities()
    )
    );
    combLearning.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combLearning, gridBagConstraints);

    jLabel33.setText(" Bằng cấp");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel33, gridBagConstraints);

    combDegree.setModel(new DefaultComboBoxModel(
        new DegreeBLL()
        .findDegreeEntities()
    ));
    combDegree.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combDegree, gridBagConstraints);

    jLabel34.setText("Ngoại ngữ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel34, gridBagConstraints);

    combForeignLanguage.setModel(new DefaultComboBoxModel(
        new ForeignLanguageBLL()
        .findForeignlanguageEntities()
    ));
    combForeignLanguage.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combForeignLanguage, gridBagConstraints);

    jLabel35.setText(" Tin học");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel35, gridBagConstraints);

    combComputing.setModel(new DefaultComboBoxModel(
        new ComputingBLL()
        .findComputingEntities()
    ));
    combComputing.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combComputing, gridBagConstraints);

    jLabel36.setText("Dân tộc");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipady = 15;
    jLayeredPane1.add(jLabel36, gridBagConstraints);

    combFolk.setModel(new DefaultComboBoxModel(
        new FolkBLL()
        .findFolkEntities()
    ));
    combFolk.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combFolk, gridBagConstraints);

    jLabel37.setText(" Quốc tịch");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel37, gridBagConstraints);

    combNationality.setModel(new DefaultComboBoxModel(
        new NationalityBLL()
        .findNationalityEntities()
    ));
    combNationality.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combNationality, gridBagConstraints);

    jLabel38.setText(" Tôn giáo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel38, gridBagConstraints);

    combReligion.setModel(new DefaultComboBoxModel(
        new ReligionBLL()
        .findReligionEntities()
    ));
    combReligion.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(combReligion, gridBagConstraints);

    jLabel39.setForeground(new java.awt.Color(255, 0, 0));
    jLabel39.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 20;
    jLayeredPane1.add(jLabel39, gridBagConstraints);

    jLabel40.setForeground(new java.awt.Color(255, 0, 0));
    jLabel40.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel40, gridBagConstraints);

    jLabel41.setForeground(new java.awt.Color(255, 0, 0));
    jLabel41.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel41, gridBagConstraints);

    jLabel42.setForeground(new java.awt.Color(255, 0, 0));
    jLabel42.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 20;
    jLayeredPane1.add(jLabel42, gridBagConstraints);

    jLabel43.setForeground(new java.awt.Color(255, 0, 0));
    jLabel43.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel43, gridBagConstraints);

    jLabel44.setForeground(new java.awt.Color(255, 0, 0));
    jLabel44.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 20;
    jLayeredPane1.add(jLabel44, gridBagConstraints);

    jLabel45.setForeground(new java.awt.Color(255, 0, 0));
    jLabel45.setText("(*)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(jLabel45, gridBagConstraints);

    txtBaseSalary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    txtBaseSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtBaseSalary.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtBaseSalaryKeyReleased(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 100;
    jLayeredPane1.add(txtBaseSalary, gridBagConstraints);

    txtSalary.setEditable(false);
    txtSalary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    txtSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 100;
    jLayeredPane1.add(txtSalary, gridBagConstraints);

    txtAllowance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    txtAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 100;
    jLayeredPane1.add(txtAllowance, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtTakenLaborPlace, gridBagConstraints);

    txtNumberLabor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jLayeredPane1.add(txtNumberLabor, gridBagConstraints);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane1)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(321, Short.MAX_VALUE)
            .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        stateButton(false);
        cleanForm();
        activeForm(true);
        action = ACTION.INSERT;
    }//GEN-LAST:event_btNewActionPerformed

    
    
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        
        toEmployee();
        if(action == ACTION.INSERT) {
            
        } else if (action == ACTION.EDIT) {
            
        }
        
        stateButton(true);
    }//GEN-LAST:event_btSaveActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        stateButton(false);
        activeForm(true);
        txtEmployeeCode.setEditable(false);
        action = ACTION.EDIT;
    }//GEN-LAST:event_btEditActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        try {
            stateButton(true);// TODO add your handling code here:
            activeForm(false);
            if (employee == null) {
                dispose();
            } else {
                loadEmployee(employee);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            if (action == ACTION.VIEW) {
                stateButton(true);
                activeForm(false);
            } else {
                stateButton(false);
                activeForm(true);

                if (action == ACTION.EDIT) {
                    txtEmployeeCode.setEditable(false);
                    loadEmployee(employee);
                } else if (action == ACTION.INSERT) {
                    cleanForm();
                }
            }

            if (employee != null) {
                loadEmployee(employee);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void calSalary(java.awt.event.KeyEvent evt) {
        try {
            // TODO add your handling code here:
            if (('0' <= evt.getKeyChar() && evt.getKeyChar() <= '9')
                    || evt.getKeyChar() == KeyEvent.VK_DELETE
                    || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE
                    || evt.getKeyChar() == KeyEvent.VK_ENTER
                    || evt.getKeyChar() == KeyEvent.VK_ESCAPE) {
                
                Long x = (Long) txtBaseSalary.getFormatter().stringToValue(txtBaseSalary.getText());
                Object y = txtCoefficient.getFormatter().stringToValue(txtCoefficient.getText());
                Object z;
                if (y instanceof Long) {
                    z = x * ((Long) y);
                } else {
                    z = (Double) y * x;
                }
                
                String k = txtSalary.getFormatter().valueToString(z);
                txtSalary.setText(k);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtBaseSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaseSalaryKeyReleased
        calSalary(evt);
    }//GEN-LAST:event_txtBaseSalaryKeyReleased

    private void txtCoefficientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoefficientKeyReleased
        // TODO add your handling code here:
        calSalary(evt);
    }//GEN-LAST:event_txtCoefficientKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }
    
    private void toEmployee() {
        
        if (employee == null) employee = new ims.dto.Employee();
        
        employee.setId(txtEmployeeCode.getText());
        employee.setFullName(txtFullName.getText());
        employee.setNickName(txtNickName.getText());
        employee.setGender(chbGender.isSelected());
        employee.setMarries(chbMarried.isSelected());
        employee.setMobieNumber(txtMobie.getText());
        employee.setPhone(txtPhone.getText());
        employee.setEmail(txtEmail.getText());
        employee.setBirthDay((Date) txtBirthDay.getValue());
        employee.setBirthPlace(txtBirthPlace.getText());
        employee.setCity((City) combCity.getSelectedItem());
        employee.setNativeLand(txtNativeLand.getText());
        employee.setAddress(txtPersonCode.getText());
        employee.setTakenPCDate((Date) txtTakenCodeDay.getValue());
        employee.setTakenPCPlace(txtTakenCodePlace.getText());
        employee.setTabernacle(txtTabernacle.getText());
        employee.setTypeStaff((Typestaff) combTypeStaff.getSelectedItem());
        employee.setStartDate((Date) txtDateStart.getValue());
        employee.setDegree((Degree) combDeparment.getSelectedItem());
        employee.setJob((Job) combJob.getSelectedItem());
        employee.setPosition((EmployeePosition) combPosition.getSelectedItem());
        employee.setBaseSalary((long) txtBaseSalary.getValue());
        employee.setFactorSalary((double) txtCoefficient.getValue());
        employee.setSalary((int) txtSalary.getValue());
        employee.setAllowedSalary((int) txtAllowance.getValue());
        employee.setBaseSalary((long) txtNumberLabor.getValue());
        employee.setTakenLaborDate((Date) txtTakenLaborDay.getValue());
        employee.setTakenLaborPlace(txtTakenCodePlace.getText());
        employee.setBankId(txtIdBank.getText());
        employee.setBank(txtBank.getText());
        employee.setLearning((Learning) combLearning.getSelectedItem());
        employee.setDegree((Degree) combDegree.getSelectedItem());
        employee.setForeignLanguage((Foreignlanguage) combForeignLanguage.getSelectedItem());
        employee.setComputing((Computing) combComputing.getSelectedItem());
        employee.setFolk((Folk) combFolk.getSelectedItem());
        employee.setNationality((Nationality) combNationality.getSelectedItem());
        employee.setReligion((Religion) combReligion.getSelectedItem());
    }
    
    private void activeForm(boolean isActive) {
        
        txtEmployeeCode.setEditable(isActive);
        txtFullName.setEditable(isActive);
        txtNickName.setEditable(isActive);
        chbGender.setEnabled(isActive);
        chbMarried.setEnabled(isActive);
        txtMobie.setEditable(isActive);
        txtPhone.setEditable(isActive);
        txtEmail.setEditable(isActive);
        txtBirthDay.setEditable(isActive);
        txtBirthPlace.setEditable(isActive);
        combCity.setEnabled(isActive);
        txtPersonCode.setEditable(isActive);
        txtTakenCodeDay.setEditable(isActive);
        txtTakenCodePlace.setEditable(isActive);
        txtNativeLand.setEditable(isActive);
        txtAddress.setEditable(isActive);
        txtTabernacle.setEditable(isActive);
        combTypeStaff.setEnabled(isActive);
        txtDateStart.setEditable(isActive);
        combDeparment.setEnabled(isActive);
        combJob.setEnabled(isActive);
        combPosition.setEnabled(isActive);
        txtBaseSalary.setEditable(isActive);
        txtCoefficient.setEditable(isActive);
        txtSalary.setEditable(false);
        txtAllowance.setEditable(isActive);
        txtNumberLabor.setEditable(isActive);
        txtTakenLaborDay.setEditable(isActive);
        txtTakenLaborPlace.setEditable(isActive);
        txtIdBank.setEditable(isActive);
        txtBank.setEditable(isActive);
        combLearning.setEnabled(isActive);
        combDegree.setEnabled(isActive);
        combForeignLanguage.setEnabled(isActive);
        combComputing.setEnabled(isActive);
        combFolk.setEnabled(isActive);
        combNationality.setEnabled(isActive);
        combReligion.setEnabled(isActive);
    }
    
    private void cleanForm() {
        
        txtEmployeeCode.setText(UtilClass.EMPTY_STRING);
        txtFullName.setText(UtilClass.EMPTY_STRING);
        txtNickName.setText(UtilClass.EMPTY_STRING);
        chbGender.setSelected(UtilClass.UNCHECKED);
        chbMarried.setSelected(UtilClass.UNCHECKED);
        txtMobie.setText(UtilClass.EMPTY_STRING);
        txtPhone.setText(UtilClass.EMPTY_STRING);
        txtEmail.setText(UtilClass.EMPTY_STRING);
        txtBirthDay.setText(UtilClass.EMPTY_STRING);
        txtBirthPlace.setText(UtilClass.EMPTY_STRING);
        combCity.setSelectedItem(UtilClass.NOSELECTEDITEM);
        txtPersonCode.setText(UtilClass.EMPTY_STRING);
        txtTakenCodeDay.setText(UtilClass.EMPTY_STRING);
        txtTakenCodePlace.setText(UtilClass.EMPTY_STRING);
        txtNativeLand.setText(UtilClass.EMPTY_STRING);
        txtAddress.setText(UtilClass.EMPTY_STRING);
        txtTabernacle.setText(UtilClass.EMPTY_STRING);
        combTypeStaff.setSelectedItem(UtilClass.NOSELECTEDITEM);
        txtDateStart.setText(UtilClass.EMPTY_STRING);
        combDeparment.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combJob.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combPosition.setSelectedItem(UtilClass.NOSELECTEDITEM);
        txtBaseSalary.setText("0");
        txtCoefficient.setText("1.00");
        txtSalary.setText("0");
        txtAllowance.setText("0");
        txtNumberLabor.setText(UtilClass.EMPTY_STRING);
        txtTakenLaborDay.setText(UtilClass.EMPTY_STRING);
        txtTakenLaborPlace.setText(UtilClass.EMPTY_STRING);
        txtIdBank.setText(UtilClass.EMPTY_STRING);
        txtBank.setText(UtilClass.EMPTY_STRING);
        combLearning.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combDegree.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combForeignLanguage.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combComputing.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combFolk.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combNationality.setSelectedItem(UtilClass.NOSELECTEDITEM);
        combReligion.setSelectedItem(UtilClass.NOSELECTEDITEM);
    }
    
    private void loadEmployee(ims.dto.Employee employee) throws ParseException {
        
        String birthDayString = txtBirthDay.getFormatter().valueToString(employee.getBirthDay());
        String personCodeDay = txtTakenCodeDay.getFormatter().valueToString(employee.getTakenPCDate());
        String startDate = txtDateStart.getFormatter().valueToString(employee.getStartDate());
        String labordate = txtTakenLaborDay.getFormatter().valueToString(employee.getTakenLaborDate());
        String salary = txtSalary.getFormatter().valueToString(employee.getSalary());
        String factorySalary = txtCoefficient.getFormatter().valueToString(employee.getFactorSalary());
        String baseLarary = txtBaseSalary.getFormatter().valueToString(employee.getBaseSalary());
        
        txtEmployeeCode.setText(employee.getId());
        txtFullName.setText(employee.getFullName());
        txtNickName.setText(employee.getNickName());
        chbGender.setSelected(employee.getGender());
        chbMarried.setSelected(employee.getMarries());
        txtMobie.setText(employee.getMobieNumber());
        txtPhone.setText(employee.getPhone());
        txtEmail.setText(employee.getEmail());
        txtBirthDay.setText(birthDayString);
        txtBirthPlace.setText(employee.getBirthPlace());
        combCity.setSelectedItem(employee.getCity());
        txtPersonCode.setText(employee.getPersonCode());
        txtTakenCodeDay.setText(personCodeDay);
        txtTakenCodePlace.setText(employee.getTakenPCPlace());
        txtNativeLand.setText(employee.getNativeLand());
        txtAddress.setText(employee.getAddress());
        txtTabernacle.setText(employee.getTabernacle());
        combTypeStaff.setSelectedItem(employee.getTypeStaff());
        txtDateStart.setText(startDate);
        combDeparment.setSelectedItem(employee.getDeparment());
        combJob.setSelectedItem(employee.getJob());
        combPosition.setSelectedItem(employee.getPosition());
        txtBaseSalary.setText(baseLarary);
        txtCoefficient.setText(factorySalary);
        txtSalary.setText(salary);
        txtAllowance.setText(String.valueOf(employee.getAllowedSalary()));
        txtNumberLabor.setText(employee.getLaborCode().toString());
        txtTakenLaborDay.setText(labordate);
        txtTakenLaborPlace.setText(employee.getTakenLaborPlace());
        txtIdBank.setText(employee.getBankId());
        txtBank.setText(employee.getBank());
        combLearning.setSelectedItem(employee.getLearning());
        combDegree.setSelectedItem(employee.getDegree());
        combForeignLanguage.setSelectedItem(employee.getForeignLanguage());
        combComputing.setSelectedItem(employee.getComputing());
        combFolk.setSelectedItem(employee.getFolk());
        combNationality.setSelectedItem(employee.getNationality());
        combReligion.setSelectedItem(employee.getReligion());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btSave;
    private javax.swing.JCheckBox chbGender;
    private javax.swing.JCheckBox chbMarried;
    private javax.swing.JComboBox<String> combCity;
    private javax.swing.JComboBox<String> combComputing;
    private javax.swing.JComboBox<String> combDegree;
    private javax.swing.JComboBox<String> combDeparment;
    private javax.swing.JComboBox<String> combFolk;
    private javax.swing.JComboBox<String> combForeignLanguage;
    private javax.swing.JComboBox<String> combJob;
    private javax.swing.JComboBox<String> combLearning;
    private javax.swing.JComboBox<String> combNationality;
    private javax.swing.JComboBox<String> combPosition;
    private javax.swing.JComboBox<String> combReligion;
    private javax.swing.JComboBox<String> combTypeStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JFormattedTextField txtAllowance;
    private javax.swing.JTextField txtBank;
    private javax.swing.JFormattedTextField txtBaseSalary;
    private javax.swing.JFormattedTextField txtBirthDay;
    private javax.swing.JTextField txtBirthPlace;
    private javax.swing.JFormattedTextField txtCoefficient;
    private javax.swing.JFormattedTextField txtDateStart;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeCode;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIdBank;
    private javax.swing.JTextField txtMobie;
    private javax.swing.JTextField txtNativeLand;
    private javax.swing.JTextField txtNickName;
    private javax.swing.JFormattedTextField txtNumberLabor;
    private javax.swing.JFormattedTextField txtPersonCode;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JFormattedTextField txtSalary;
    private javax.swing.JTextField txtTabernacle;
    private javax.swing.JFormattedTextField txtTakenCodeDay;
    private javax.swing.JTextField txtTakenCodePlace;
    private javax.swing.JFormattedTextField txtTakenLaborDay;
    private javax.swing.JTextField txtTakenLaborPlace;
    // End of variables declaration//GEN-END:variables
}
